// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:habitroot/features/product/model/product.dart';
import 'package:habitroot/features/store/model/store.dart';
import 'package:habitroot/features/user/model/app_user.dart';
import 'package:habitroot/old_feature/habit/domain/habit.dart';
import 'package:habitroot/old_feature/notification/domain/reminder.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppUserAdapter());
    registerAdapter(HabitAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(ReminderAdapter());
    registerAdapter(StoreAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppUserAdapter());
    registerAdapter(HabitAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(ReminderAdapter());
    registerAdapter(StoreAdapter());
  }
}
